services:
  pbitrading-app:
    image: pbitrading-app:latest
    container_name: pbitrading-app
    ports:
      - "90:80"   # ← port 8090 du VPS → port 80 du container
    restart: always
    environment:
      - NODE_ENV=production